### ISSUE TITLE
Removal Of 1bot!

### ISSUE THREAD

**Issue by ombhatt2** [thatjar/1bot#6]
The owner of the bot is bad and he claims that this repo is open source but if you use it then he will raid your server!

**Comment by thatjar** [comment]
Yeah sure... 🤡

If it raids your server, your bot would raid servers too, because you literally copied and pasted all of 1Bot's code and called it your own.

> claims this repo is open source

^ That's not how things work, please check what open source even means.

I can't think of a more polite way to say.. "get a life".
I highly recommend getting a life, instead of cloning bots and claiming them as your own, raiding servers, review-bombing, etc etc.

You've cloned bots twice before already, with Atlanta and BotGhost.
Yes, I know this, because I checked the Top.gg logs.

**Comment by V3ntus** [comment]
No
